//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kütüphane_projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kullanici
    {
        public int KullaniciID { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSoyad { get; set; }
        public string KullaniciTc { get; set; }
        public string KullaniciPasNo { get; set; }
        public string KullaniciTel { get; set; }
        public string KullaniciMail { get; set; }
        public string KullaniciKadi { get; set; }
        public string KullaniciSifre { get; set; }
        public string SonGiris { get; set; }
    }
}
