//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kütüphane_projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kitap()
        {
            this.tbl_Emanet = new HashSet<tbl_Emanet>();
        }
    
        public int KitapID { get; set; }
        public string BarkodNo { get; set; }
        public string KitapAdi { get; set; }
        public string Yazar { get; set; }
        public Nullable<int> BaskiYili { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public string Yayinevi { get; set; }
        public string Türü { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emanet> tbl_Emanet { get; set; }
    }
}
