//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kütüphane_projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emanet
    {
        public int EmanetID { get; set; }
        public Nullable<int> EmanetKitapId { get; set; }
        public Nullable<int> EmanetUyeId { get; set; }
        public Nullable<System.DateTime> EmanetVertarih { get; set; }
        public Nullable<System.DateTime> EmanetAltarih { get; set; }
        public Nullable<bool> EmanetDurum { get; set; }
    
        public virtual tbl_Uyeler tbl_Uyeler { get; set; }
        public virtual tbl_Kitap tbl_Kitap { get; set; }
    }
}
